name: Deploy Dev

on:
  workflow_run:
    workflows: ["Build Sign Publish"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image tag in manifests
        run: |
          sed -i "s|ghcr.io/victord-ef/orders-service:dev|ghcr.io/${{ github.repository_owner }}/orders-service:${{ github.event.workflow_run.head_sha }}|g" deploy/base/orders-deployment.yaml

      - name: Validate manifests
        run: kubectl kustomize deploy/overlays/dev > /tmp/dev-rendered.yaml
